### ISSUE TITLE
Page break is missing

### ISSUE THREAD

**Issue by clickwork-git** [bludit-themes/typerite#2]
Page break ("Read more") is missing.

**Comment by dignajar** [comment]
Hi Edi,
the template doesn't provide a button read more.

https://www.styleshout.com/free-templates/typerite/

**Comment by clickwork-git** [comment]
Okay, I understand.

**Comment by dignajar** [comment]
We can implement it, just a read more text at the bottom.
But is not a bug.
Keep open the ticket to remember me.

**Comment by dignajar** [comment]
I include a read more button as a link also release a new version.
https://github.com/bludit-themes/typerite/releases/tag/1.1
