### ISSUE TITLE
Header Nav Bar not rendering properly on iOS

### ISSUE THREAD

**Issue by JustJoao** [bludit-themes/typerite#3]
Hi, 
The navbar is not displayed on iOS, despite being clickable. I'm using Typewrite v1.1, you can use this as a demo: 
https://joaobotelho.pt/bludit/

Here's a screenshot from iPad (mini 4): 
![imagem](https://user-images.githubusercontent.com/17578730/71515449-8ab32d00-28a3-11ea-828f-9ff07f30cdeb.png)
http://joaobotelho.pt/arq10/bl-themes/ipad-wrong.jpg

This is how it was supposed to look (based on device preview on PC):
![imagem](https://user-images.githubusercontent.com/17578730/71515464-9f8fc080-28a3-11ea-9c15-b338d74f5b19.png)

And here's a screenshot from iPhone (SE):
![imagem](https://user-images.githubusercontent.com/17578730/71515516-e7164c80-28a3-11ea-925d-c230090220b3.png)

**Comment by i-am-stef** [comment]
Did you find a fix for it? Having the same problem right now. Thanks!

**Comment by klaus1958** [comment]
Hi, seems you have solved it,as I see when cecking your website. What was the problem? Thx for your answer: Klaus

**Comment by i-am-stef** [comment]
Hi, yeah I somehow managed to make it work a little, though would not call it fixed. Unfortunately I forgot what I did as I played around a lot (I am not good with CSS at all) but will attach my main.css file, hope it helps. 

[main.css.zip](https://github.com/bludit-themes/typerite/files/4671845/main.css.zip)

**Comment by clickwork-git** [comment]
Fixed in v1.2.
